const keys = {
  movieGenres: "movieGenres",
  trendingMovies: "trendingMovies",
  koreanMovies: "koreanMovies",
  topRatedMovies: "topRatedMovies",
  animeMovies: "animeMovies",
  tvShowGenres: "tvShowGenres",
  trendingTvShows: "trendingTvShows",
  koreanDramas: "koreanDramas",
  topRatedTvShows: "topRatedTvShows",
  animeTvShows: "animeTvShows",
  popupMovies: "popupMovies",
  popupTvShows: "popupTvShows",
  searchedMovies: "searchedMovies",
  searchedTvShows: "searchedTvShows",
  movie: "movie",
  tvShow: "tvShow",
  movieCasts: "movieCasts",
  tvShowCasts: "tvShowCasts",
  moviePosters: "moviePosters",
  tvShowPosters: "tvShowPosters",
  movieVideos: "movieVideos",
  tvShowVideos: "tvShowVideos",
};

export default keys;
